def build_nginx_failure_plan(query: str) -> dict:
    return {
        "id": "plan_demo_nginx_failure",
        "goal": "诊断 nginx 启动失败原因",
        "user_query": query,
        "intent": "service_failure_diagnosis",
        "safety_level": "readonly_diagnosis",
        "scope": {
            "services": ["nginx"],
            "ports": [80, 443],
            "logs": ["nginx.service"],
        },
        "forbidden_actions": [
            "delete_file",
            "modify_config",
            "read_sensitive_file",
            "stop_unrelated_service",
        ],
        "required_evidence": [
            "service_status",
            "error_log",
            "port_occupancy",
            "network_context",
            "lsof_process_context",
            "process_owner",
        ],
        "steps": [
            {
                "id": "step_1",
                "tool": "systemctl_status",
                "args": {"service": "nginx"},
                "risk": "readonly",
                "reason": "先确认 nginx.service 的真实运行状态，避免凭日志猜测。",
                "expected_evidence": "service_status",
            },
            {
                "id": "step_2",
                "tool": "journalctl_unit",
                "args": {"unit": "nginx", "lines": 80},
                "risk": "readonly",
                "reason": "读取最近错误日志，寻找 bind、权限、配置等失败信号。",
                "expected_evidence": "error_log",
            },
            {
                "id": "step_3",
                "tool": "ss_listen",
                "args": {"port": 80},
                "risk": "readonly",
                "reason": "验证 nginx 默认端口是否已被其他进程监听。",
                "expected_evidence": "port_occupancy",
            },
            {
                "id": "step_4",
                "tool": "netstat_listen",
                "args": {"port": 80},
                "risk": "readonly",
                "reason": "使用 netstat 交叉验证监听端口与进程线索，满足 OS 网络上下文感知要求。",
                "expected_evidence": "network_context",
            },
            {
                "id": "step_5",
                "tool": "lsof_port",
                "args": {"port": 80},
                "risk": "readonly",
                "reason": "使用 lsof 查看端口关联进程与用户，补充进程级上下文。",
                "expected_evidence": "lsof_process_context",
            },
            {
                "id": "step_6",
                "tool": "ps_process",
                "args": {"pid": "$from_port_evidence"},
                "risk": "readonly",
                "reason": "追踪端口占用 PID 的进程身份，形成可审计根因链。",
                "expected_evidence": "process_owner",
            },
        ],
    }
